# Generated by Django 2.2.6 on 2019-10-04 03:37

from django.db import migrations, models
import filestorages


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=filestorages.get_storage('some.defined.storage'), upload_to='')),
            ],
        ),
    ]
